import type { Metadata } from "next";
import "@/ui/globals.css";
import {oswald,inter,karrik,zenAntique} from "@/ui/fonts";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 在这里进行next支持的font的挂载 */}
      <body
        className={`antialiased min-w-[1200px] ${oswald.variable} ${inter.variable} ${karrik.variable} ${zenAntique.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
